### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by caoziyang1997** [IRVLUTD/Proto-CLIP#16]
raceback (most recent call last):
  File "/home/czy/project/SYF/Proto-CLIP/beit.py", line 412, in <module>
    main()
  File "/home/czy/project/SYF/Proto-CLIP/beit.py", line 374, in main
    dataset = ImageNet(cfg['root_path'], cfg['shots'], transform)
  File "/home/czy/project/SYF/Proto-CLIP/datasets/imagenet.py", line 212, in __init__
    self.train = torchvision.datasets.ImageNet(
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 46, in __init__
    self.parse_archives()
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 59, in parse_archives
    parse_devkit_archive(self.root)
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 140, in parse_devkit_archive
    _verify_archive(root, file, md5)
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 96, in _verify_archive
    raise RuntimeError(msg.format(file, root))
RuntimeError: The archive ILSVRC2012_devkit_t12.tar.gz is not present in the root directory or is corrupted. You need to download it externally and place it in DATRuntimeError: The archive ILSVRC2012_devkit_t12.tar.gz is not present in the root directory or is corrupted. You need to download it externally and place it in DATA/imagenet/images.
(proto-clip) czy@cluster02-X785-G30:~/project/SYF/Proto-CLIP$ CUDA_VISIBLE_DEVICES=0 python beit.py --config configo/imagenet.yml --dataset imagenet

Running configs.
{'root_path': 'DATA', 'shots': 16, 'backbone': 'RN50', 'dataset': 'imagenet', 'only_test': False, 'lr': 0.0001, 'augment_epoch': 10, 'train_epoch': 2000, 'alpha': 0.5, 'beta': 12, 'adapter': 'conv-2x', 'train_vis_mem_only': True, 'losses': ['L1', 'L2', 'L3'], 'cache_dir': './caches/imagenet'}

Load ckpt from ./beit3/beit3_large_itc_patch16_224.pth
Load state_dict by model_key = model
batch_size:  256
Preparing dataset.
Traceback (most recent call last):
  File "/home/czy/project/SYF/Proto-CLIP/beit.py", line 412, in <module>
    main()
  File "/home/czy/project/SYF/Proto-CLIP/beit.py", line 374, in main
    dataset = ImageNet(cfg['root_path'], cfg['shots'], transform)
  File "/home/czy/project/SYF/Proto-CLIP/datasets/imagenet.py", line 212, in __init__
    self.train = torchvision.datasets.ImageNet(
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 46, in __init__
    self.parse_archives()
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 59, in parse_archives
    parse_devkit_archive(self.root)
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 140, in parse_devkit_archive
    _verify_archive(root, file, md5)
  File "/home/czy/anaconda3/envs/proto-clip/lib/python3.10/site-packages/torchvision/datasets/imagenet.py", line 96, in _verify_archive
    raise RuntimeError(msg.format(file, root))
RuntimeError: The archive ILSVRC2012_devkit_t12.tar.gz is not present in the root directory or is corrupted. You need to download it externally and place it in DATA/imagenet/images.

**Comment by jishnujayakumar** [comment]
Hi @caoziyang1997 

Thank you for reaching out!

For information on how to download and set up the ImageNet dataset, please refer to the following guide: [ImageNet Dataset Installation](https://github.com/IRVLUTD/Proto-CLIP/blob/main/DATASET.md#imagenet). This guide should help you with the correct steps to avoid errors.

Unfortunately, I’m unable to share a pre-downloaded version of the ImageNet dataset. However, the guide should provide you with the necessary instructions to successfully download and set up the dataset on your own. If you have any further questions or encounter any issues, feel free to ask!

**Comment by caoziyang1997** [comment]
> Hi @caoziyang1997
> 
> Thank you for reaching out!
> 
> For information on how to download and set up the ImageNet dataset, please refer to the following guide: [ImageNet Dataset Installation](https://github.com/IRVLUTD/Proto-CLIP/blob/main/DATASET.md#imagenet). This guide should help you with the correct steps to avoid errors.
> 
> Unfortunately, I’m unable to share a pre-downloaded version of the ImageNet dataset. However, the guide should provide you with the necessary instructions to successfully download and set up the dataset on your own. If you have any further questions or encounter any issues, feel free to ask!

The ImageNet dataset I downloaded has the same validation and test sets when running. Is this correct？
![image](https://github.com/user-attachments/assets/8448665c-c2d0-4365-9d0a-dc0fe2e18596)

**Comment by jishnujayakumar** [comment]
> > Hi @caoziyang1997
> > Thank you for reaching out!
> > For information on how to download and set up the ImageNet dataset, please refer to the following guide: [ImageNet Dataset Installation](https://github.com/IRVLUTD/Proto-CLIP/blob/main/DATASET.md#imagenet). This guide should help you with the correct steps to avoid errors.
> > Unfortunately, I’m unable to share a pre-downloaded version of the ImageNet dataset. However, the guide should provide you with the necessary instructions to successfully download and set up the dataset on your own. If you have any further questions or encounter any issues, feel free to ask!
> 
> The ImageNet dataset I downloaded has the same validation and test sets when running. Is this correct？ ![image](https://private-user-images.githubusercontent.com/61769948/360212286-8448665c-c2d0-4365-9d0a-dc0fe2e18596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODkwODAsIm5iZiI6MTcyNDI4ODc4MCwicGF0aCI6Ii82MTc2OTk0OC8zNjAyMTIyODYtODQ0ODY2NWMtYzJkMC00MzY1LTlkMGEtZGMwZmUyZTE4NTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTJjZTM5ZDdmM2M1Nzk0YTVkYzBmMTIxZTNlZDY0NzllMTFhMDliZGNjOTRlNWRkYWZmYjIzZTBlOWQ2MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8RSASRVX1Qr_1Cibi0t1JoR63i4vCg5cH-O6Axyor74)

Yes.
